<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard1.6;net45</TargetFrameworks>
    <FSharpCoreImplicitPackageVersion>4.1.*</FSharpCoreImplicitPackageVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.1</Version>
    <Authors>Christer van der Meeren;Stefano Pian</Authors>
    <Description>AsyncResult and Result computation expressions and helper functions for error handling in F#.</Description>
    <PackageLicenseUrl>https://github.com/cmeeren/Cvdm.ErrorHandling/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/cmeeren/Cvdm.ErrorHandling</PackageProjectUrl>
    <PackageTags>f# error-handling computation-expression asyncresult async result</PackageTags>
    <PackageReleaseNotes>Fix potential crash bug when throwing from async and catching/finalizing in asyncResult</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="ResultBuilder.fs" />
    <Compile Include="AsyncResultBuilder.fs" />
    <Compile Include="Helpers.fs" />
  </ItemGroup>

  <!-- Add source files to package for Fable compatibility -->
  <ItemGroup>
    <Content Include="*.fsproj; *.fs" PackagePath="fable\" />
  </ItemGroup>

</Project>
